# Generated by Django 5.0.6 on 2024-05-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photoFileName', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('fiber', models.FloatField()),
                ('vitaminA', models.FloatField()),
                ('vitaminB', models.FloatField()),
                ('vitaminC', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iodine', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('zing', models.FloatField()),
                ('data', models.TextField(blank=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myAPI.users')),
            ],
        ),
        migrations.CreateModel(
            name='EatenFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.food')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.users')),
            ],
        ),
    ]
