# Generated by Django 5.0.6 on 2024-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='zing',
            new_name='zinc',
        ),
    ]
